name: website update

on:
  push:
    paths:
      - 'doc/**'
      - 'web/**'
  workflow_dispatch:

jobs:
  web_update:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        cd doc
        pip3 install -r requirements.txt
        cd OSL
        python3 make_osl_document.py
        cd ..
        python3 docgen.py
        cd ..
        curl -s -O https://nvgt.gg/ci/static/cobalt.exe
        cd web
        ../cobalt build
        cd public_html
        tar -czf ../../public_html.tar.gz *
        cd ../..
        curl -u "${{secrets.CIFTP}}" -s -T public_html.tar.gz ftp://nvgt.gg
        curl -H "X-Auth: ${{secrets.CIPHP}}" -s https://nvgt.gg/ci/website_update.php
